"use strict";
let miNumero = 10;
miNumero = 10 + 456;
miNumero = 2.5;
miNumero = 2.5 + 2.5;
console.log(miNumero);
let booleano = true;
booleano = false;
let encendido;
//console.log(encendido);
encendido = true;
console.log('Encendido es: ', encendido);
console.log('Encendido es: ', { encendido });
encendido = true && false;
console.log(encendido);
encendido = false && true;
encendido = false && false;
console.log('Resultado', encendido);
let normal = 'Hola';
normal = 10;
normal = true;
normal = 11.25;
console.log('Normal', normal);
